export enum EnumModalAction {
  SHOW_AUTH_MODAL = 'SHOW_AUTH_MODAL',
  SHOW_ADD_BUDGET_MODAL = 'SHOW_ADD_BUDGET_MODAL',
  SHOW_PROF_MODAL = 'SHOW_PROF_MODAL',
  SHOW_ALERT_MODAL = ' SHOW_ALERT_MODAL',
  CLOSE_MODAL = 'CLOSE_MODAL',
}
export type TModalAuthStatus = 'login' | 'reg';
